version: '3.8'

services:
  task-service:
    build: .
#    volumes:
#     - ./tasks-service:/app
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=task-db
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_NAME=tasks
      - DB_PORT=5432
      - USER_SERVICE_ADDR=users-service:50051 
    depends_on:
      - task-db
    networks:
      - app-network
    restart: unless-stopped

  task-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=tasks
    ports:
      - "5438:5432"
    volumes:
      - task_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  task_db_data:

networks:
  app-network:
    external: true